funciones_cripto.h File Reference
#include <iostream>
Functions
void Usage (int argc, char *argv[])
Muestra el modo de uso correcto del programa En caso de que el uso no sea el correcto, se muestra el mensaje y finaliza con la ejecución del programa.
bool Entero (const string str)
Comprueba si la string que se introduce es un entero.
bool Parametrosvalidos (char *argv[])
Comprueba que los parámetros introducidos en el programa son válidos.
string Cesar (string message, int key)
Efectúa el cifrado/descifrado césar.
string XOR (string message, string key)
Efectúa el cifrado/descifrado XOR.
Variables
const string kHelpText
Function Documentation
Cesar()
string Cesar (string texto, int f)
Efectúa el cifrado/descifrado césar.
Parameters
 in texto String que contiene el mensaje.
 in f constante de rotación
Returns
Mensaje cifrado/descifrado utilizando César
Definition at line 83 of file funciones_cripto.cc.
                                  {
  string encrypted_texto{""};
  for (auto t : texto) {
    encrypted_texto.push_back(t + (char)f);
  }
  return encrypted_texto;
}
Referenced by main().
Entero()
bool Entero (string number)
Comprueba si la string que se introduce es un entero.
Parameters
 in number String que contiene el número.
Returns
si el número es un entero.
Definition at line 68 of file funciones_cripto.cc.
                           {
  for (auto t : number) {
    if (t < 48 || t > 57) return false;
  }
  return true;
}
Referenced by Parametrosvalidos().
Parametrosvalidos()
bool Parametrosvalidos (char * argv[])
Comprueba que los parámetros introducidos en el programa son válidos.
Parameters
 in argv Vector (char*) que contiene los parámetros
Returns
si los parámetros son válidos
Definition at line 50 of file funciones_cripto.cc.
                                     {
  if (argv[3][0] != '1' && argv[3][0] != '2') return false;
  string parameter_4{argv[4]};
  if (argv[3][0] == '2' && !Entero(parameter_4)) {
    return false;
  }
  if (argv[5][0] != '+' && argv[5][0] != '-') return false;
  return true;
}
References Entero().
Referenced by main().
Usage()
void Usage (int argc, char * argv[])
Muestra el modo de uso correcto del programa En caso de que el uso no sea el correcto, se muestra el mensaje y finaliza con la ejecución del programa.
El programa precisa de 5 parámetros para su ejecución:
Fichero de entrada
Fichero de salida
Método de cifrado
Password
Operación a usar (+: cifrar, -: descifrar)
Parameters
 in argc Número de parámetros de línea de comandos
 in argv Vector (char*) que contiene los parámetros
Definition at line 25 of file funciones_cripto.cc.
                                   {
  if (argc == 2) {
    string parameter{argv[1]};
    if (parameter == "--help") {
      cout << argv[0] << " -- Cifrado de ficheros\n";
      cout << "Modo de uso: " << argv[0]
                << " fichero_entrada fichero_salida método password operación\n";
      std::cout << kHelpText << "\n";
      exit(EXIT_SUCCESS);
    }
  }
  if (argc == 1 || argc != 6) {
    cout << argv[0] << " -- Cifrado de ficheros\n";
    cout << "Modo de uso: " << argv[0]
              << " fichero_entrada fichero_salida método password operación\n";
    cout << "Pruebe " << argv[0] << " --help para más información\n";
        exit(EXIT_SUCCESS);
  }
}
References kHelpText.
Referenced by main().
XOR()
string XOR (string texto, string key)
Efectúa el cifrado/descifrado XOR.
Parameters
 in texto String que contiene el texto.
 in key String que contiene la key.
Returns
Mensaje cifrado/descifrado utilizando XOR.
Definition at line 98 of file funciones_cripto.cc.
                                     {
  string encrypted_key{""};
  string encrypted_texto{""};
  for (size_t i = 0; i < key.length(); i++) {
    char xored_char = key.at(i) ^ (char)128;
    encrypted_key.push_back(xored_char);
  }
  for (size_t i = 0; i < texto.length(); i++) {
    char xored_char =
        texto.at(i) ^ encrypted_key.at(i % encrypted_key.length());
    encrypted_texto.push_back(xored_char);
  }
  return encrypted_texto;
}
Referenced by main().
Variable Documentation
kHelpText
const string kHelpText
Initial value:
= R"(fichero_entrada: Fichero a codificar
fichero_salida: Fichero codificado
método: Indica el método de encriptado
                   1: Cifrado xor
                   2: Cifrado de César
password: Palabra secreta en el caso de método 1, Valor de K en el método 2
operación: Operación a realizar en el fichero
                   +: encriptar el fichero
                   -: desencriptar el fichero)"
Definition at line 11 of file funciones_cripto.h.
Referenced by Usage().